router:
  ip: 'http://192.168.1.1'
  user: 'root'
  password: ''
admin-ip:
  - '192.168.0.140'
  - '192.168.0.141'
admin-telegram-id:
  - 518325236
  - 864662054
  - 839840272
music-path: 'z:\музыка'
whitelist-path: '/etc/qwert.txt'
files-path: 'd:/'