summer-mode: false

router:
  ip: '192.168.1.1'
  user: 'root'

db:
  host: 'localhost'
  port: 5432
  database: 'vympel.one'
  user: 'postgres'

mqtt:
  host: 'localhost'
  port: 1883
  buttons-topic: 'buttons'
  laser-topic: ''

host: 'localhost'
snapdrop-host: 'vympel.one'

admin-telegram-id:
  - 518325236
  - 864662054
  - 839840272
  - 1061060541
admin-ip:
  - '192.168.0.100'
  - '192.180.0.18'
ph-ip:
  - '192.168.0.47'
  - '192.168.0.48'

photo-use-year: true
year: 2024
shift: 1
music-path: 'z:/музыка/дискотека 2.0'
photo-path: 'z:/фото'
now-photo-path: 'z:/фото/{year}/{shift} поток'
archives-path: 'z:/фото/архивы/{year}/{shift} поток'
presentation-path: 'z:/вд/{year}/{shift} поток'
exclude-photo-path:
  - педсостав
  - скрины
  - фотографирование
whitelist-path: '/etc/qwert.txt'

monitor-path: 'z:/вд/{year}/1 поток'

disco-dates:
  - 03.07.2023
  - 05.07.2023
  - 07.07.2023
  - 09.07.2023
  - 10.07.2023
  - 13.07.2023
  - 15.07.2023
  - 22.07.2023
  - 24.07.2023
  - 26.07.2023
  - 27.07.2023
  - 01.08.2023
  - 03.08.2023
  - 04.08.2023
  - 10.08.2023
  - 12.08.2023
  - 13.08.2023
  - 14.08.2023
  - 16.08.2023
  - 18.08.2023
  - 21.08.2023
  - 22.08.2023

album_ids:
  - "вымпелevent":
      - 301288665
  - "масленица":
      - 301347176
  - "1 поток":
      - 301347177
  - "2 поток":
      - 301347180
  - "3 поток":
      - 301347182
  - "4 поток":
      - 301347183



squads:
  squad_1:
    name: Киберпингви
    slogan: Киберпингви я люблю!
    registration-date: 21.07.2023
    squad-size: 32
    balance: загрузка...
    logo: 1_squad.png
  squad_2:
    name: Земля будущего
    slogan: Мы направляем свет, где нас нет, чтобы наступил рассвет!
    registration-date: 21.07.2023
    squad-size: 34
    balance: загрузка...
    logo: 2_squad.png
  squad_3:
    name: Флешики
    slogan: Флешиков девиз наш мил – пришел, увидел, победил!
    registration-date: 21.07.2023
    squad-size: 43
    balance: загрузка...
    logo: 3_squad.png
  squad_4:
    name: Пиксели
    slogan: Пиксели – маленькие, мы – велики, знаем, дойдем до конца игры!
    registration-date: 21.07.2023
    squad-size: 38
    balance: загрузка...
    logo: 4_squad.png
  squad_5:
    name: Педсостав
    slogan: Мы рождены, чтоб сказку сделать былью
    registration-date: 01.06.1964
    squad-size: 25
    balance: бюджет созвездия
    logo: 5_squad.png
