router:
  ip: '192.168.1.1'
  user: 'root'

db:
  host: '192.168.0.100'
  port: 5432
  database: 'vympel.one'
  user: 'postgres'

host: '192.170.0.181'
snapdrop-host: '192.168.0.100'

admin-telegram-id:
  - 518325236
  - 864662054
  - 839840272
  - 1061060541
admin-ip:
  - '192.170.0.181'
  - '192.170.0.117'
  - '192.168.0.100'
ph-ip:
  - '192.170.0.181'
  - '192.168.0.100'

music-path: 'z:/музыка/дискотека'
archives-path: 'z:/фото/архивы/2023/1 поток/'
whitelist-path: '/etc/qwert.txt'
photo-path: 'z:/фото'
now-photo-path: 'z:/фото/2023/1 поток'
monitor-path: 'z:/вд/2023/1 поток'

disco-dates:
  - 01.06.2023

squads:
  squad_1:
    slogan: ћы рождены, чтоб сказку сделать былью
    registration-date: 01.06.1960
    squad-size: 25
    balance: загрузка...
    logo: no_image.png
  squad_2:
    slogan: ћы рождены, чтоб сказку сделать былью
    registration-date: 01.06.1961
    squad-size: 25
    balance: загрузка...
    logo: no_image.png
  squad_3:
    slogan: ћы рождены, чтоб сказку сделать былью
    registration-date: 01.06.1962
    squad-size: 25
    balance: загрузка...
    logo: no_image.png
  squad_4:
    slogan: ћы рождены, чтоб сказку сделать былью
    registration-date: 01.06.1963
    squad-size: 25
    balance: загрузка...
    logo: no_image.png
  squad_5:
    slogan: ћы рождены, чтоб сказку сделать былью
    registration-date: 01.06.1964
    squad-size: 25
    balance: бюджет созвезди€
    logo: no_image.png

album_ids:
  - "масленица":
      - 293714146
  - "1 поток":
      - 293714166
  - "2 поток":
      - 293714172
  - "3 поток":
      - 293714178
  - "4 поток":
      - 293714184