router:
  ip: '192.168.1.1'
  user: 'root'
  password: 'pusdes69'
host: 'http://192.170.0.181'
admin-ip:
  - '192.170.0.181'
  - '192.168.0.100'
ph-ip:
  - '192.170.0.181'
  - '192.168.0.100'
admin-telegram-id:
  - 518325236
  - 864662054
  - 839840272
  - 1061060541
music-path: 'z:/музыка/дискотека'
files-path: 'z:/фото/архивы/2023/1 поток/'
whitelist-path: '/etc/qwert.txt'
photo-path: 'z:/фото'
now-photo-path: 'z:\фото\2023\1 поток'
monitor-path: 'z:/вд/2023/1 поток'
album_ids:
  - "масленица":
      - 293714146
  - "1 поток":
      - 293714166
  - "2 поток":
      - 293714172
  - "3 поток":
      - 293714178
  - "4 поток":
      - 293714184